config/routes.rb
Rails.application.routes.draw do
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :description, presence: true
  validates :price_per_night, presence: true, numericality: { only_integer: true }
  validates :number_of_guests, presence: true, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: %i[show edit update destroy]

  def index
    @flats = Flat.all

    if params[:query].present?
      @query = params[:query]
      @flats = Flat.where("name LIKE ?", "%#{params[:query]}%")
      raise
    else
      @flats = Flat.all
    end
  end

  # hidden_field_tag

  def show; end
  def edit; end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.create(flat_params)
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @flat.update(flat_params)
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @flat.destroy
    redirect_to flat_path, status: :see_other
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_banner.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to 'Simple AirBnB', flats_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
    </div>
    <form class="d-flex" role="search">
      <input class="form-control me-2" type="search" aria-label="Search" value="<%= params[:query]%>">
      <button class="btn btn-outline-primary" type="submit">Search</button>
    </form>
    <%= link_to 'Add Flat', new_flat_path, class: "btn btn-outline-warning ms-2" %>
  </div>
</nav>

app/views/flats/_form.html.erb
  <%= simple_form_for flat do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.submit "Create flat", class: "btn btn-warning mb-3" %>
  <% end %>

app/views/flats/edit.html.erb
<%= render "banner" %>
<div class="container">
  <h1>Edit property</h1>
  <%= render "form", flat: @flat %>
</div>

app/views/flats/index.html.erb
<%= render "banner" %>

<div class="container mt-3">
  <div class="row">
    <h1 class="mt-2 col-12">All our properties</h1>
  </div>
  <div class="row">
    <p class="col-12">All <%= @flats.count %> properties</p>
  </div>
  <div class="row">
    <% @flats.each do |flat| %>
      <div class="col-md-4">
        <div class="flat-card">
          <div class="flat-card-image" style="background-image: url('https://images.unsplash.com/photo-1534212758080-135b3affa932?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2071&q=80')"></div>
            <div class="flat-card-content">
            <h4><%= flat.name %></h4>
            <p><%= flat.address %></p>
            <div class="flex">
              <div class="flex align-items-center">
                <i class="fa-solid fa-people-line me-1"></i>
                <span><%= flat.number_of_guests %></span>
              </div>
              <div class="flex align-items-center ms-3">
                <i class="fa-solid fa-euro-sign me-1"></i>
                <span><%= flat.price_per_night %></span>
              </div>
            </div>
            </div>
            <div class="flat-card-actions">
              <span class="text-primary">
                <%= link_to 'More info', flat_path(flat) %>
              </span>
              <span class="ms-3">
                <%= link_to 'Edit', edit_flat_path(flat), class: "text-warning" %>
              </span>
              <span class="ms-3 text-danger">
              <%= link_to "Remove",
                flat_path(flat),
                data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},
                class: "text-danger"
              %>
              </span>
            </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<%= render "banner" %>
<div class="container">
  <h1 class="my-3">Add a property</h1>
  <%= render "form", flat: @flat %>
</div>

app/views/flats/show.html.erb
<%= render "banner" %>

<div class="map" style="background-image: url('https://images.unsplash.com/photo-1532188978303-4bfaccc429d2?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80')"></div>

<div class="container margin-top-negative">
  <div class="row show-row">
    <div class="col-8">
      <div class="flat-show-card">
        <h1><%= @flat.name %></h1>
        <p class="flat-show-address"><%= @flat.address %></p>
      </div>
      <div class="flat-show-card">
        <h3>A bit more about this flat...</h3>
        <p><%= @flat.description %></p>
        <div class="map" style="background-image: url('https://images.unsplash.com/photo-1569336415962-a4bd9f69cd83?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1031&q=80')"></div>
      </div>
    </div>

  <div class="col-4">
    <div class="flat-show-card">
      <h5>Book this place</h5>
      <form action="">
        <div class="input-group">
          <span class="input-group-text" id="start-date-label">From:</span>
          <input type="text" class="form-control" placeholder="12/10/2017" aria-label="start-date" aria-describedby="start-date-label">
        </div>
        <div class="input-group mt-2">
          <span class="input-group-text" id="end-date-label">To:</span>
          <input type="text" class="form-control" placeholder="18/10/2017" aria-label="end-date" aria-describedby="start-date-label">
        </div>
        <input type="submit" value="Book" class="btn btn-primary mt-2" style="width: 100%">
      </form>
    </div>

    <div class="flat-show-card">
      <h3>Details</h3>
      <div class="flex">
        <div class="flex"><%= @flat.number_of_guests %> people</div>
        <div class="flex ms-3"><%= @flat.price_per_night %>€</div>
      </div>
    </div>

    <div class="flat-show-card">
      <div class="flex-align">
        <h6 class="no-mb">Share</h6>
        <div class="flex">
          <i class="fa-brands fa-facebook-square me-2"></i>
          <i class="fa-brands fa-twitter-square me-2"></i>
          <i class="fa-brands fa-pinterest-square me-2"></i>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>